import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

course=pd.read_csv('/Users/paimatho/Desktop/Python/pandas/merjing_joining_concating/data/courses.csv')
month1=pd.read_csv('/Users/paimatho/Desktop/Python/pandas/merjing_joining_concating/data/reg-month1.csv')
month2=pd.read_csv('/Users/paimatho/Desktop/Python/pandas/merjing_joining_concating/data/reg-month2.csv')
student=pd.read_csv('/Users/paimatho/Desktop/Python/pandas/merjing_joining_concating/data/students.csv')

delivery=pd.read_csv('/Users/paimatho/Desktop/Python/pandas/merjing_joining_concating/data/deliveries.csv')
matches=pd.read_csv('/Users/paimatho/Desktop/Python/pandas/merjing_joining_concating/data/matches.csv')

# pd.concat :- verticaly concata two or more file help of this command
reg=pd.concat([month1,month2],ignore_index=True) # ignore index besicaly crate new index after concating data
print(reg)

# multi index data fram means table have more than 1 index
multi=pd.concat([month1,month2],keys=['month1','month2'])
print(multi)

# horigontaly concat 
total=total=pd.concat([month1,month2],axis=1)
print(total)


# join 
# inner join
ij=student.merge(reg,how='inner',on='student_id').sort_values('student_id')
print(ij)

# left join
lf=course.merge(reg,how='left',on="course_id")
print(lf)

# right join :- right join have all right parts
# outer join :- outer join have all left and right both parts are availble

# Q find the total revenue generated by compney
price=reg.merge(course,how='inner',on='course_id')
print("Total revenue is",price['price'].sum())

# Q2. find month by month revenue
month=pd.concat([month1,month2],keys=['month1','month2']).reset_index()
price=month.merge(course,on='course_id').groupby('level_0')
print(price['price'].sum())

# Q3 Print the egistration table like name->course->price
final=reg.merge(student,on='student_id').merge(course,on='course_id')
print(final[['name','course_name','price']])

# Q4 ploat bar chart for revenue / course
chart=reg.merge(course,on='course_id').groupby('course_name')['price'].sum()
chart.plot(kind='bar')
plt.show()


